import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { unlink } from 'fs/promises';
import { resolve } from 'path';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class MediaService {
  constructor(private readonly prisma: PrismaService) {}

  async create(tenantId: string, file: Express.Multer.File) {
    if (!file) throw new BadRequestException('No file provided');
    return this.prisma.mediaAsset.create({
      data: {
        tenantId,
        filename: file.originalname,
        mimeType: file.mimetype,
        sizeBytes: file.size,
        storageKey: file.filename,
      },
    });
  }

  list(tenantId: string) {
    return this.prisma.mediaAsset.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'desc' },
      take: 200,
    });
  }

  async findOne(tenantId: string, id: string) {
    const m = await this.prisma.mediaAsset.findFirst({ where: { id, tenantId } });
    if (!m) throw new NotFoundException('Media not found');
    return m;
  }

  /** Public lookup by id only — used by IG/TikTok to fetch the file. */
  async findPublic(id: string) {
    return this.prisma.mediaAsset.findUnique({ where: { id } });
  }

  async remove(tenantId: string, id: string) {
    const m = await this.findOne(tenantId, id);
    await this.prisma.mediaAsset.delete({ where: { id } });
    try {
      await unlink(this.absolutePath(m.storageKey));
    } catch {
      // file already gone — fine
    }
    return { ok: true };
  }

  absolutePath(storageKey: string): string {
    const dir = resolve(process.env.UPLOAD_DIR || '/app/uploads');
    // Prevent path traversal — storageKey is generated by multer but stay defensive.
    if (storageKey.includes('..') || storageKey.includes('/') || storageKey.includes('\\')) {
      throw new BadRequestException('Invalid storage key');
    }
    return resolve(dir, storageKey);
  }

  /** Public, internet-reachable URL the social providers can fetch from. */
  publicUrl(id: string): string {
    const base = process.env.APP_URL || 'http://localhost:3000';
    return `${base}/api/media/${id}/raw`;
  }
}
